name: CI
on: push
jobs:
  deploy:
   
    runs-on: ubuntu-latest
    if: github.ref == 'refs/head/main'
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying, because this is main"
  
