name: CI
on: [push, pull_request]
jobs:
  deploy:
    runs-on: ubuntu-latest
    if : github.ref == 'ref/heads/main'
    steps:
      - uses: actions/checkout@v4
      - run: echo "Deploying, because this main"
        
