name: CI
on: push
jobs: 
  linit:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v4
     - run: echo "Linit step running"
  test: 
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - run: echo "Test step running"
